backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "src/img/"
public_folder: "/img/"
collections: 
  - name: "photos"
    label: "photos"
    folder: "src/portfolio-img"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tag", widget: "list", allow_add: false}